In [1]:
import numpy as np 
import pandas as pd
print('da')

da

In [2]:
dict1={
    "name":["a","b","c"],
    "age":[11,18,12],
    "city":['pune','napur','mumbai']
    
}
print(dict1)

{'name': ['a', 'b', 'c'], 'age': [11, 18, 12], 'city': ['pune', 'napur', 'mumbai']}

In [3]:
#TODO create  dataframe df "df is like excel sheet for faster indexing "

df=pd.DataFrame(dict1)
df
#df.head()

  name  age    city
0    a   11    pune
1    b   18   napur
2    c   12  mumbai

In [4]:
# how to add data to excel sheet
df.to_csv('friend.csv')
# to remove index from from csv
#df.to_csv('friend.csv',index=False)

In [5]:
df.head(2)

  name  age   city
0    a   11   pune
1    b   18  napur

In [6]:
df.tail(2)

  name  age    city
1    b   18   napur
2    c   12  mumbai

In [7]:
df.describe()

             age
count   3.000000
mean   13.666667
std     3.785939
min    11.000000
25%    11.500000
50%    12.000000
75%    15.000000
max    18.000000

In [8]:
co2_df=pd.read_csv("../input/fuelconsumption/FuelConsumption_file.csv")

In [9]:
co2_df

,Unnamed: 0,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [10]:
co2_df.head()

,Unnamed: 0,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [11]:
co2_df.tail()

,Unnamed: 0,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
1062,1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [12]:
co2_df.describe()

,Unnamed: 0,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.000000,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,533.000000,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,308.160672,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,0.000000,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,266.500000,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,533.000000,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,799.500000,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,1066.000000,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [13]:
#data fram and series
ser=pd.Series(np.random.rand(34))

In [14]:
ser.head()

0    0.651372
1    0.463954
2    0.737660
3    0.555244
4    0.645037
dtype: float64

In [15]:
newdf=pd.DataFrame(np.random.rand(334,14),index=np.arange(334))

In [16]:
newdf.head(50)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.740945,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
5,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420
6,0.270739,0.918678,0.782818,0.656755,0.832907,0.867386,0.871221,0.347840,0.734728,0.402319,0.965438,0.437558,0.307564,0.168659
7,0.964141,0.424993,0.479642,0.696465,0.547333,0.320971,0.336461,0.783859,0.109886,0.847526,0.162009,0.508324,0.298644,0.146836
8,0.706073,0.134621,0.163621,0.805855,0.644710,0.407460,0.034313,0.223859,0.463595,0.301779,0.722180,0.736331,0.835565,0.158005
9,0.818131,0.650622,0.999113,0.417567,0.134442,0.081784,0.700179,0.268041,0.789126,0.683780,0.644940,0.074384,0.164911,0.103723
10,0.328356,0.345511,0.535832,0.409851,0.030436,0.438366,0.338602,0.591528,0.080707,0.679146,0.147283,0.099552,0.723764,0.800996
11,0.127300,0.000554,0.799000,0.036371,0.260473,0.042422,0.319489,0.755905,0.231627,0.327860,0.339529,0.185159,0.224568,0.896521
12,0.429707,0.887536,0.424673,0.610423,0.524072,0.690679,0.637293,0.536949,0.793066,0.829156,0.477147,0.993380,0.127403,0.983407
13,0.130303,0.796574,0.050794,0.030741,0.311935,0.102227,0.436356,0.765887,0.174430,0.954433,0.766410,0.975375,0.138793,0.036513
14,0.906300,0.739569,0.914946,0.148255,0.453524,0.139830,0.540842,0.166376,0.844771,0.805827,0.243214,0.342289,0.989429,0.601760
15,0.342849,0.336574,0.515101,0.786418,0.920027,0.488576,0.853537,0.474963,0.929179,0.812764,0.409753,0.725634,0.198211,0.656849
16,0.235082,0.310225,0.528945,0.896170,0.456423,0.589532,0.436559,0.069517,0.815499,0.455103,0.625906,0.134908,0.112287,0.769656
17,0.274165,0.173581,0.856471,0.267772,0.397649,0.908203,0.935502,0.812750,0.688129,0.040162,0.413266,0.290341,0.340913,0.218606
18,0.101345,0.482370,0.922639,0.749181,0.795641,0.487602,0.712964,0.574396,0.483824,0.337615,0.457690,0.113928,0.244695,0.953712
19,0.057381,0.017402,0.497720,0.986170,0.949358,0.275483,0.006172,0.690779,0.048764,0.283610,0.574985,0.470440,0.987753,0.778178
20,0.975151,0.711131,0.986074,0.103724,0.092085,0.204077,0.064221,0.285712,0.905932,0.167923,0.428075,0.497972,0.757467,0.829448
21,0.140329,0.816931,0.155438,0.871750,0.726996,0.993268,0.848922,0.182172,0.345605,0.507148,0.582408,0.750043,0.419739,0.893128
22,0.286240,0.140454,0.222127,0.707845,0.293360,0.901359,0.544213,0.047100,0.943640,0.773887,0.098145,0.660928,0.221716,0.705407
23,0.579760,0.845373,0.429023,0.015112,0.489218,0.592585,0.567973,0.955149,0.301695,0.010052,0.385287,0.180454,0.401888,0.159462
24,0.951865,0.531186,0.216487,0.826270,0.568252,0.659057,0.331807,0.209305,0.853348,0.608550,0.519446,0.669992,0.924815,0.776122
25,0.423663,0.409180,0.402374,0.126542,0.599978,0.268798,0.786412,0.605581,0.689165,0.747977,0.029879,0.159924,0.157857,0.346034
26,0.172797,0.405116,0.336574,0.085972,0.764842,0.261521,0.744349,0.949944,0.351931,0.166384,0.174364,0.958559,0.859615,0.446779
27,0.352586,0.106594,0.277859,0.232000,0.453143,0.551408,0.601983,0.549136,0.199517,0.115204,0.900637,0.469153,0.726144,0.424475
28,0.067406,0.458840,0.616235,0.420921,0.714323,0.174498,0.473349,0.091053,0.982618,0.074412,0.957062,0.105868,0.895315,0.773704
29,0.918205,0.596798,0.638643,0.145924,0.096283,0.530061,0.168777,0.157543,0.895045,0.212196,0.883751,0.931800,0.604514,0.080482
30,0.011037,0.879223,0.966382,0.637227,0.142272,0.317458,0.422331,0.196025,0.369335,0.418475,0.265095,0.972262,0.145240,0.761341
31,0.863173,0.123428,0.805030,0.697493,0.465357,0.992902,0.790086,0.817468,0.910958,0.243963,0.475394,0.444645,0.611549,0.410885
32,0.294175,0.178539,0.207884,0.022028,0.680040,0.460162,0.125176,0.390289,0.898395,0.059254,0.099367,0.518153,0.943036,0.500488
33,0.975229,0.350771,0.521727,0.541469,0.037009,0.527965,0.507545,0.320633,0.581514,0.949552,0.858561,0.724515,0.378761,0.622797
34,0.183953,0.825657,0.483298,0.208883,0.462662,0.403375,0.005167,0.895358,0.614662,0.755425,0.601625,0.303311,0.692525,0.943080
35,0.457644,0.494566,0.532400,0.596330,0.501981,0.693026,0.170154,0.197201,0.812010,0.833012,0.161344,0.874280,0.278405,0.513008
36,0.771551,0.906581,0.098799,0.134191,0.087698,0.038517,0.585596,0.768099,0.457196,0.654794,0.253654,0.730895,0.095339,0.965837
37,0.607439,0.901878,0.495482,0.623970,0.381483,0.532325,0.142288,0.718304,0.398805,0.189452,0.407217,0.471575,0.229403,0.251259
38,0.218479,0.541903,0.051466,0.265745,0.007863,0.398939,0.166892,0.870786,0.763774,0.172155,0.542866,0.051295,0.130657,0.345233
39,0.990708,0.545041,0.238989,0.756518,0.121237,0.727499,0.486191,0.739155,0.220353,0.545632,0.534161,0.122675,0.743454,0.078488
40,0.398225,0.928826,0.391193,0.045353,0.665223,0.506372,0.091763,0.993982,0.577658,0.381935,0.053030,0.007911,0.392353,0.452496
41,0.124255,0.825292,0.045154,0.707242,0.495146,0.569803,0.877276,0.317300,0.836032,0.873652,0.922519,0.023680,0.954857,0.670275
42,0.435067,0.946513,0.754267,0.964677,0.338203,0.921959,0.053380,0.096026,0.901402,0.613900,0.042420,0.937751,0.438046,0.904395
43,0.839653,0.105557,0.020659,0.810266,0.759825,0.290171,0.892371,0.240298,0.613843,0.205986,0.970609,0.918267,0.507930,0.473173
44,0.145849,0.406092,0.226038,0.178585,0.914192,0.395096,0.106331,0.254115,0.626578,0.271283,0.179924,0.582357,0.542591,0.863275
45,0.213122,0.455867,0.738837,0.491654,0.492087,0.041099,0.368903,0.908132,0.334181,0.261478,0.281716,0.428740,0.710657,0.316014
46,0.660209,0.323477,0.169138,0.230405,0.014089,0.985238,0.241690,0.168079,0.812594,0.351766,0.193830,0.996825,0.118379,0.818076
47,0.183138,0.069993,0.469642,0.976415,0.061473,0.251793,0.716160,0.432094,0.675042,0.026634,0.088583,0.192114,0.813309,0.917498
48,0.866643,0.508148,0.479590,0.102818,0.026253,0.439075,0.982927,0.431655,0.534490,0.242532,0.506391,0.679103,0.700645,0.431389
49,0.466347,0.081963,0.094426,0.641970,0.370322,0.206961,0.301439,0.033163,0.467043,0.967508,0.339059,0.573577,0.340508,0.695353

In [17]:
newdf.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
count,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000
mean,0.486478,0.477868,0.501818,0.509423,0.502397,0.480473,0.488506,0.511048,0.516821,0.488194,0.485325,0.487128,0.495696,0.512379
std,0.282771,0.300309,0.293641,0.291729,0.290359,0.286562,0.280893,0.301579,0.287098,0.280438,0.287477,0.287855,0.286747,0.288141
min,0.001749,0.000287,0.000585,0.008842,0.002625,0.001900,0.005167,0.002130,0.006013,0.003214,0.002682,0.007911,0.002887,0.000849
25%,0.238054,0.198124,0.231661,0.257072,0.246276,0.236394,0.235398,0.238156,0.276028,0.250107,0.239501,0.243035,0.244362,0.254230
50%,0.469623,0.470352,0.506074,0.496376,0.506172,0.467862,0.484229,0.492024,0.520438,0.506111,0.481417,0.473800,0.467720,0.517362
75%,0.745297,0.759987,0.753691,0.756324,0.752425,0.738792,0.717174,0.783620,0.769452,0.721777,0.738667,0.725354,0.738077,0.763081
max,0.999721,0.999988,0.999113,0.999795,0.999690,0.996407,0.999327,0.998843,0.994037,0.994468,0.997073,0.996825,0.996244,0.995013

In [18]:
newdf.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
dtype: object

In [19]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.740945,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257

In [20]:
newdf.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
           dtype='int64', length=334)

In [21]:
newdf.columns

RangeIndex(start=0, stop=14, step=1)

In [22]:
#df to array
newdf.to_numpy()

array([[0.74094479, 0.99462524, 0.80507864, ..., 0.41466677, 0.00288737,
        0.93183541],
       [0.89625554, 0.72839954, 0.93669659, ..., 0.53671264, 0.56120672,
        0.27240603],
       [0.68181435, 0.29785022, 0.74778556, ..., 0.36749957, 0.15132181,
        0.21708374],
       ...,
       [0.21472311, 0.18956063, 0.49739827, ..., 0.88764417, 0.6351394 ,
        0.73311142],
       [0.38272323, 0.06301663, 0.67830265, ..., 0.79600392, 0.61733188,
        0.18596552],
       [0.21810639, 0.12169394, 0.36161113, ..., 0.95028599, 0.71077634,
        0.74470694]])

In [23]:
newdf[0][0]='string'

In [24]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,string,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257

In [25]:
newdf[0][0]=0.3

In [26]:
newdf.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084

In [27]:
newdf[0][0]=0.3

In [28]:
#how to do transpose in df
newdf.T
#rows to col. col to row

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.896256,0.681814,0.783995,0.441515,0.300276,0.270739,0.964141,0.706073,0.818131,...,0.308064,0.68637,0.431333,0.328547,0.167055,0.824135,0.115959,0.214723,0.382723,0.218106
1,0.994625,0.7284,0.29785,0.006656,0.300986,0.940422,0.918678,0.424993,0.134621,0.650622,...,0.412033,0.332368,0.89461,0.295051,0.551703,0.201497,0.984018,0.189561,0.063017,0.121694
2,0.805079,0.936697,0.747786,0.523332,0.776341,0.124293,0.782818,0.479642,0.163621,0.999113,...,0.964726,0.075052,0.236403,0.027732,0.632047,0.787859,0.191009,0.497398,0.678303,0.361611
3,0.656086,0.361487,0.423973,0.833554,0.568652,0.227924,0.656755,0.696465,0.805855,0.417567,...,0.343109,0.174974,0.969945,0.999795,0.741156,0.921937,0.547945,0.730148,0.220339,0.74648
4,0.853333,0.997399,0.544111,0.596404,0.922948,0.586139,0.832907,0.547333,0.64471,0.134442,...,0.370052,0.458502,0.417283,0.791018,0.455336,0.256191,0.087737,0.320034,0.17503,0.106143
5,0.736625,0.405734,0.275802,0.153211,0.794423,0.956553,0.867386,0.320971,0.40746,0.081784,...,0.285124,0.601234,0.541407,0.395088,0.527487,0.704336,0.607947,0.758658,0.596211,0.524207
6,0.010856,0.421339,0.893851,0.177945,0.131636,0.20137,0.871221,0.336461,0.034313,0.700179,...,0.231751,0.015992,0.465035,0.604308,0.844925,0.311462,0.421043,0.406578,0.465139,0.499034
7,0.782628,0.770723,0.588789,0.880661,0.290941,0.656149,0.34784,0.783859,0.223859,0.268041,...,0.094147,0.731027,0.825356,0.684787,0.540394,0.365352,0.271646,0.675829,0.85054,0.17216
8,0.3652,0.740426,0.085202,0.340201,0.99392,0.567066,0.734728,0.109886,0.463595,0.789126,...,0.692141,0.683127,0.925409,0.728459,0.909506,0.071169,0.878964,0.160257,0.725302,0.020308
9,0.529898,0.281968,0.763629,0.540135,0.800529,0.806271,0.402319,0.847526,0.301779,0.68378,...,0.95891,0.021034,0.417371,0.414767,0.627292,0.897106,0.244585,0.680381,0.458937,0.523951
10,0.219119,0.677125,0.266094,0.442634,0.042324,0.669934,0.965438,0.162009,0.72218,0.64494,...,0.781486,0.515918,0.154297,0.370031,0.102051,0.099156,0.562389,0.048956,0.846075,0.527995
11,0.414667,0.536713,0.3675,0.234342,0.586363,0.667483,0.437558,0.508324,0.736331,0.074384,...,0.263013,0.330665,0.265062,0.471052,0.009631,0.648493,0.159432,0.887644,0.796004,0.950286
12,0.002887,0.561207,0.151322,0.890863,0.466696,0.5036,0.307564,0.298644,0.835565,0.164911,...,0.819879,0.71503,0.005287,0.708208,0.637714,0.05876,0.183929,0.635139,0.617332,0.710776
13,0.931835,0.272406,0.217084,0.409542,0.747257,0.53942,0.168659,0.146836,0.158005,0.103723,...,0.68149,0.771442,0.904741,0.797062,0.232082,0.315881,0.168176,0.733111,0.185966,0.744707

In [29]:
#sorting in row
newdf.sort_index(axis=0,ascending=False)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
0,0.3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835

In [30]:
#sarting in col
newdf.sort_index(axis=1,ascending=False)

,13,12,11,10,9,8,7,6,5,4,3,2,1,0
0,0.931835,0.002887,0.414667,0.219119,0.529898,0.365200,0.782628,0.010856,0.736625,0.853333,0.656086,0.805079,0.994625,0.3
1,0.272406,0.561207,0.536713,0.677125,0.281968,0.740426,0.770723,0.421339,0.405734,0.997399,0.361487,0.936697,0.728400,0.896256
2,0.217084,0.151322,0.367500,0.266094,0.763629,0.085202,0.588789,0.893851,0.275802,0.544111,0.423973,0.747786,0.297850,0.681814
3,0.409542,0.890863,0.234342,0.442634,0.540135,0.340201,0.880661,0.177945,0.153211,0.596404,0.833554,0.523332,0.006656,0.783995
4,0.747257,0.466696,0.586363,0.042324,0.800529,0.993920,0.290941,0.131636,0.794423,0.922948,0.568652,0.776341,0.300986,0.441515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.315881,0.058760,0.648493,0.099156,0.897106,0.071169,0.365352,0.311462,0.704336,0.256191,0.921937,0.787859,0.201497,0.824135
330,0.168176,0.183929,0.159432,0.562389,0.244585,0.878964,0.271646,0.421043,0.607947,0.087737,0.547945,0.191009,0.984018,0.115959
331,0.733111,0.635139,0.887644,0.048956,0.680381,0.160257,0.675829,0.406578,0.758658,0.320034,0.730148,0.497398,0.189561,0.214723
332,0.185966,0.617332,0.796004,0.846075,0.458937,0.725302,0.850540,0.465139,0.596211,0.175030,0.220339,0.678303,0.063017,0.382723
333,0.744707,0.710776,0.950286,0.527995,0.523951,0.020308,0.172160,0.499034,0.524207,0.106143,0.746480,0.361611,0.121694,0.218106

In [31]:
newdf[0]
print("it`s type is ",type(newdf[0]))

it`s type is  <class 'pandas.core.series.Series'>

In [32]:
newdf2=newdf
#here newdf2 is not copinf newdf value but it just refrencing the val

In [33]:
newdf2[0][0]='set in newdf2'

In [34]:
newdf
#newdf is having changes we made in newdf2
#same a pass by refrance' ie. newdf2 is view of newdf

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,set in newdf2,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707

In [35]:
newdf3=newdf.copy()

In [36]:
newdf3

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,set in newdf2,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707

In [37]:
newdf3[0][0]='set in new df3'

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [38]:
newdf
# no changes to df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,set in newdf2,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707

In [39]:
newdf2[0][0]=2323
#this does not have any garety of when it will return view and when it will return copy 
#this we use lock

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [40]:
newdf.loc[0,0]=22

In [41]:
newdf.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,22,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406

In [42]:
newdf.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,22,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406

In [43]:
newdf3.columns=list('asdfghjklpoiuy')

In [44]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707

In [45]:
#how to add new col to trable
newdf3[0]=898

In [46]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406,898
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898

In [47]:
#how to delete in table in df
#how to delete  a row
newdf3.drop(0)
# how to delete a coloum
newdf3.drop(0,axis=1)

,a,s,d,f,g,h,j,k,l,p,o,i,u,y
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707

In [48]:
#newdf3.drop((0,0),axis=1)

In [49]:
newdf3.loc[[1,2],['a','s']]

          a        s
1  0.896256  0.72840
2  0.681814  0.29785

In [50]:
newdf3.loc[[1,2],:]

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
1,0.896256,0.72840,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406,898
2,0.681814,0.29785,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898

In [51]:
newdf3.loc[:,['a','s']]

                  a         s
0    set in new df3  0.994625
1          0.896256  0.728400
2          0.681814  0.297850
3          0.783995  0.006656
4          0.441515  0.300986
..              ...       ...
329        0.824135  0.201497
330        0.115959  0.984018
331        0.214723  0.189561
332        0.382723  0.063017
333        0.218106  0.121694

[334 rows x 2 columns]

In [52]:
newdf3.loc[newdf3['s']>0.373329]

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406,898
5,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420,898
6,0.270739,0.918678,0.782818,0.656755,0.832907,0.867386,0.871221,0.347840,0.734728,0.402319,0.965438,0.437558,0.307564,0.168659,898
7,0.964141,0.424993,0.479642,0.696465,0.547333,0.320971,0.336461,0.783859,0.109886,0.847526,0.162009,0.508324,0.298644,0.146836,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,0.370471,0.405806,0.667232,0.447740,0.008307,0.030320,0.688670,0.331777,0.785043,0.590335,0.163339,0.080313,0.003082,0.196078,898
324,0.308064,0.412033,0.964726,0.343109,0.370052,0.285124,0.231751,0.094147,0.692141,0.958910,0.781486,0.263013,0.819879,0.681490,898
326,0.431333,0.894610,0.236403,0.969945,0.417283,0.541407,0.465035,0.825356,0.925409,0.417371,0.154297,0.265062,0.005287,0.904741,898
328,0.167055,0.551703,0.632047,0.741156,0.455336,0.527487,0.844925,0.540394,0.909506,0.627292,0.102051,0.009631,0.637714,0.232082,898
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898

In [53]:
newdf3.loc[(newdf3['s']>0.373329) & (newdf3['g']>0.5)]

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406,898
5,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420,898
6,0.270739,0.918678,0.782818,0.656755,0.832907,0.867386,0.871221,0.347840,0.734728,0.402319,0.965438,0.437558,0.307564,0.168659,898
7,0.964141,0.424993,0.479642,0.696465,0.547333,0.320971,0.336461,0.783859,0.109886,0.847526,0.162009,0.508324,0.298644,0.146836,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,0.077,0.490992,0.512169,0.154718,0.671753,0.396562,0.951253,0.187475,0.142049,0.579842,0.987195,0.973602,0.951366,0.416053,898
312,0.897799,0.604512,0.969826,0.468131,0.876222,0.581458,0.350727,0.352799,0.156471,0.732532,0.249257,0.266748,0.184125,0.716049,898
314,0.438177,0.984118,0.011472,0.211652,0.522202,0.118219,0.077883,0.261349,0.098366,0.443749,0.160278,0.359904,0.416716,0.405026,898
319,0.291946,0.884330,0.207921,0.194104,0.543973,0.799944,0.276054,0.508618,0.532283,0.565322,0.185846,0.363452,0.689253,0.047298,898
320,0.747866,0.966676,0.720663,0.430408,0.565262,0.312987,0.115503,0.977935,0.280479,0.029879,0.119052,0.360119,0.766008,0.049542,898

In [54]:
# loc for selcting row and col with ther index name 
# Iloc  for inreting using counting 
newdf3.iloc[0,11]

0.4146667699600274

In [55]:
newdf3.iloc[[0,1],[2,5]]
# this is saying to select  0th and 1 st row and select 2nd and 5th col only

          d         h
0  0.805079  0.736625
1  0.936697  0.405734

In [56]:
newdf3.drop(['a'],axis=1)

,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406,898
2,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
3,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
4,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
330,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
331,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
332,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
333,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898

In [57]:
newdf3.drop([1])

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
5,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898

In [58]:
newdf3
#even after dropin newdf3 is not showing any changes this is because we have not saved it newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,0.896256,0.728400,0.936697,0.361487,0.997399,0.405734,0.421339,0.770723,0.740426,0.281968,0.677125,0.536713,0.561207,0.272406,898
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898

In [59]:
#newdf3=newdf3.drop([1])
#or use in   place
newdf3.drop([1],inplace=True)

In [60]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
5,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898

In [61]:
# now in newdf3 indix is not proper so we will use reset_index()
newdf3.reset_index()

,index,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,2,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
2,3,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
3,4,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
4,5,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,329,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
329,330,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
330,331,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
331,332,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
332,333,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898

In [62]:
newdf3.reset_index(drop=True ,inplace=True)

In [63]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.994625,0.805079,0.656086,0.853333,0.736625,0.010856,0.782628,0.365200,0.529898,0.219119,0.414667,0.002887,0.931835,898
1,0.681814,0.297850,0.747786,0.423973,0.544111,0.275802,0.893851,0.588789,0.085202,0.763629,0.266094,0.367500,0.151322,0.217084,898
2,0.783995,0.006656,0.523332,0.833554,0.596404,0.153211,0.177945,0.880661,0.340201,0.540135,0.442634,0.234342,0.890863,0.409542,898
3,0.441515,0.300986,0.776341,0.568652,0.922948,0.794423,0.131636,0.290941,0.993920,0.800529,0.042324,0.586363,0.466696,0.747257,898
4,0.300276,0.940422,0.124293,0.227924,0.586139,0.956553,0.201370,0.656149,0.567066,0.806271,0.669934,0.667483,0.503600,0.539420,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,0.824135,0.201497,0.787859,0.921937,0.256191,0.704336,0.311462,0.365352,0.071169,0.897106,0.099156,0.648493,0.058760,0.315881,898
329,0.115959,0.984018,0.191009,0.547945,0.087737,0.607947,0.421043,0.271646,0.878964,0.244585,0.562389,0.159432,0.183929,0.168176,898
330,0.214723,0.189561,0.497398,0.730148,0.320034,0.758658,0.406578,0.675829,0.160257,0.680381,0.048956,0.887644,0.635139,0.733111,898
331,0.382723,0.063017,0.678303,0.220339,0.175030,0.596211,0.465139,0.850540,0.725302,0.458937,0.846075,0.796004,0.617332,0.185966,898
332,0.218106,0.121694,0.361611,0.746480,0.106143,0.524207,0.499034,0.172160,0.020308,0.523951,0.527995,0.950286,0.710776,0.744707,898