In [1]:
import numpy as np 
import pandas as pd
print('da')

da

In [2]:
dict1={
    "name":["a","b","c"],
    "age":[11,18,12],
    "city":['pune','napur','mumbai']
    
}
print(dict1)

{'name': ['a', 'b', 'c'], 'age': [11, 18, 12], 'city': ['pune', 'napur', 'mumbai']}

In [3]:
#TODO create  dataframe df "df is like excel sheet for faster indexing "

df=pd.DataFrame(dict1)
df
#df.head()

  name  age    city
0    a   11    pune
1    b   18   napur
2    c   12  mumbai

In [4]:
# how to add data to excel sheet
df.to_csv('friend.csv')
# to remove index from from csv
#df.to_csv('friend.csv',index=False)

In [5]:
df.head(2)

  name  age   city
0    a   11   pune
1    b   18  napur

In [6]:
df.tail(2)

  name  age    city
1    b   18   napur
2    c   12  mumbai

In [7]:
df.describe()

             age
count   3.000000
mean   13.666667
std     3.785939
min    11.000000
25%    11.500000
50%    12.000000
75%    15.000000
max    18.000000

In [8]:
co2_df=pd.read_csv("../input/fuelconsumption/FuelConsumption_file.csv")

In [9]:
co2_df

,Unnamed: 0,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [10]:
co2_df.head()

,Unnamed: 0,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [11]:
co2_df.tail()

,Unnamed: 0,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
1062,1062,2014,VOLVO,XC60 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1063,1063,2014,VOLVO,XC60 AWD,SUV - SMALL,3.2,6,AS6,X,13.2,9.5,11.5,25,264
1064,1064,2014,VOLVO,XC70 AWD,SUV - SMALL,3.0,6,AS6,X,13.4,9.8,11.8,24,271
1065,1065,2014,VOLVO,XC70 AWD,SUV - SMALL,3.2,6,AS6,X,12.9,9.3,11.3,25,260
1066,1066,2014,VOLVO,XC90 AWD,SUV - STANDARD,3.2,6,AS6,X,14.9,10.2,12.8,22,294

In [12]:
co2_df.describe()

,Unnamed: 0,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.000000,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,533.000000,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,308.160672,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,0.000000,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,266.500000,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,533.000000,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,799.500000,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,1066.000000,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [13]:
#data fram and series
ser=pd.Series(np.random.rand(34))

In [14]:
ser.head()

0    0.125363
1    0.520158
2    0.780790
3    0.099152
4    0.276973
dtype: float64

In [15]:
newdf=pd.DataFrame(np.random.rand(334,14),index=np.arange(334))

In [16]:
newdf.head(50)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.301842,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.321130,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.132730,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.600360,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
5,0.726246,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390
6,0.671892,0.897207,0.980766,0.455676,0.793246,0.007508,0.724472,0.224628,0.288958,0.573188,0.782551,0.991958,0.767585,0.190958
7,0.495993,0.756652,0.974579,0.674198,0.139226,0.802499,0.411549,0.890752,0.788237,0.939648,0.093825,0.170354,0.659827,0.261276
8,0.294247,0.122952,0.319315,0.350012,0.658908,0.780787,0.501845,0.741650,0.866401,0.944687,0.688265,0.190980,0.766680,0.617571
9,0.895273,0.117256,0.417497,0.488571,0.601607,0.150280,0.080019,0.574512,0.028771,0.992232,0.746190,0.012970,0.970513,0.528129
10,0.617756,0.015957,0.547373,0.659514,0.123511,0.407484,0.325381,0.554805,0.816147,0.544922,0.413331,0.973162,0.882765,0.924274
11,0.223027,0.061867,0.751879,0.345344,0.085033,0.560936,0.884250,0.168837,0.042939,0.971945,0.984368,0.908856,0.745685,0.097482
12,0.651057,0.565026,0.706130,0.008148,0.111146,0.797779,0.200034,0.661736,0.049854,0.409705,0.733795,0.043632,0.325940,0.997400
13,0.671920,0.134230,0.818774,0.620990,0.182425,0.726549,0.018268,0.140199,0.536235,0.454674,0.638791,0.423740,0.373067,0.946182
14,0.322953,0.940453,0.010036,0.831912,0.765228,0.990996,0.976712,0.019947,0.759003,0.649417,0.779131,0.862146,0.606184,0.829191
15,0.810786,0.743600,0.059281,0.131701,0.179661,0.218432,0.455494,0.135651,0.826851,0.379701,0.613949,0.204986,0.325399,0.101473
16,0.511204,0.132973,0.565126,0.214744,0.360425,0.214357,0.803999,0.919016,0.256210,0.080352,0.650229,0.420561,0.294066,0.873622
17,0.612306,0.991646,0.148961,0.329158,0.837378,0.033708,0.775600,0.094713,0.005186,0.178107,0.826827,0.172680,0.667112,0.688812
18,0.554851,0.685161,0.685254,0.441138,0.456217,0.927580,0.910149,0.750367,0.087621,0.784172,0.503114,0.665405,0.009765,0.642746
19,0.101181,0.851229,0.170784,0.961363,0.466875,0.436390,0.044492,0.794370,0.217923,0.754162,0.017906,0.895397,0.259582,0.158534
20,0.060835,0.558492,0.508832,0.147093,0.605710,0.113900,0.191879,0.089944,0.756549,0.454460,0.397893,0.123209,0.756689,0.555887
21,0.291275,0.776038,0.915001,0.126259,0.405039,0.427236,0.830234,0.072604,0.576630,0.882836,0.955985,0.157829,0.490707,0.622432
22,0.066972,0.411588,0.205257,0.199507,0.942242,0.298297,0.695760,0.853264,0.353958,0.770286,0.107057,0.211072,0.902950,0.789315
23,0.697730,0.508558,0.690323,0.679161,0.745304,0.172167,0.913148,0.272550,0.168965,0.854804,0.993250,0.322593,0.236962,0.744696
24,0.387891,0.602586,0.968448,0.040089,0.877017,0.904147,0.342932,0.130018,0.869549,0.424973,0.008141,0.979354,0.442786,0.854591
25,0.737655,0.062421,0.428423,0.162654,0.746434,0.010935,0.902981,0.256912,0.866607,0.279832,0.873976,0.950286,0.493783,0.066421
26,0.519825,0.525149,0.286717,0.798125,0.938305,0.435592,0.693248,0.120523,0.155858,0.981699,0.607918,0.773355,0.299302,0.268413
27,0.926490,0.924336,0.636051,0.903313,0.633352,0.992202,0.165066,0.654321,0.272933,0.425096,0.308772,0.466641,0.063256,0.825288
28,0.338258,0.084948,0.049158,0.769283,0.514106,0.317301,0.690821,0.889901,0.437603,0.035501,0.422787,0.492436,0.072200,0.868071
29,0.084530,0.217226,0.162973,0.800807,0.086897,0.558087,0.194418,0.519815,0.017145,0.947274,0.871487,0.106916,0.490699,0.570903
30,0.134776,0.135577,0.282224,0.780353,0.017354,0.533868,0.558445,0.176493,0.184180,0.353553,0.734845,0.944908,0.672915,0.576095
31,0.779259,0.872185,0.126867,0.674634,0.971799,0.931077,0.601319,0.462676,0.949377,0.886588,0.506581,0.938366,0.551480,0.298573
32,0.630568,0.351621,0.909338,0.823507,0.439351,0.414786,0.911120,0.477199,0.815447,0.087522,0.219454,0.715068,0.789460,0.984651
33,0.363654,0.479601,0.394817,0.524290,0.581168,0.810307,0.086349,0.876323,0.524810,0.906482,0.291222,0.211675,0.804970,0.396876
34,0.479048,0.233270,0.732028,0.024421,0.341649,0.005748,0.285214,0.929476,0.642842,0.622803,0.066163,0.019804,0.306699,0.076478
35,0.876475,0.029367,0.179805,0.994205,0.488536,0.136473,0.789612,0.443322,0.917732,0.974292,0.522891,0.500023,0.846407,0.516987
36,0.324586,0.475605,0.261146,0.063995,0.202549,0.540197,0.965679,0.244041,0.518524,0.717188,0.100718,0.405529,0.125299,0.218564
37,0.293380,0.319439,0.218923,0.357677,0.761144,0.616005,0.092121,0.098684,0.916066,0.418204,0.069434,0.954239,0.044727,0.732402
38,0.107847,0.338048,0.393446,0.667513,0.321008,0.878632,0.020414,0.138805,0.696024,0.501326,0.971001,0.768614,0.623557,0.054601
39,0.352106,0.531031,0.161776,0.371847,0.354119,0.481684,0.579891,0.525477,0.445612,0.508830,0.864988,0.520654,0.291692,0.545211
40,0.174875,0.647131,0.463573,0.161485,0.824574,0.330583,0.149284,0.418101,0.571370,0.928889,0.257660,0.140315,0.284972,0.484146
41,0.997092,0.362387,0.371415,0.103007,0.088499,0.441654,0.014289,0.430019,0.468735,0.728883,0.813921,0.801609,0.656833,0.975061
42,0.504706,0.577790,0.807447,0.088807,0.901275,0.799946,0.861936,0.870790,0.711504,0.184187,0.370072,0.378884,0.190195,0.174619
43,0.496078,0.155062,0.161330,0.212065,0.643986,0.766269,0.819925,0.381924,0.517502,0.311156,0.865793,0.750388,0.812083,0.506712
44,0.901461,0.612548,0.133840,0.181703,0.153471,0.320168,0.044146,0.881768,0.642072,0.387028,0.120967,0.161773,0.892864,0.861470
45,0.929414,0.101720,0.864643,0.635154,0.729594,0.822452,0.667843,0.053869,0.065320,0.308151,0.691453,0.300177,0.639315,0.405672
46,0.532775,0.988814,0.674300,0.806469,0.369046,0.868689,0.296138,0.833770,0.485007,0.284066,0.653208,0.114544,0.880412,0.901417
47,0.666298,0.879559,0.001961,0.779121,0.562581,0.898137,0.007873,0.641329,0.260405,0.102852,0.769299,0.204760,0.029728,0.649688
48,0.571777,0.992556,0.961793,0.465520,0.356725,0.794367,0.392294,0.135034,0.488592,0.049536,0.625623,0.701472,0.939297,0.035226
49,0.780367,0.927095,0.352765,0.174751,0.927242,0.393869,0.624289,0.292986,0.774205,0.883683,0.537624,0.303067,0.215006,0.131795

In [17]:
newdf.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
count,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000
mean,0.493247,0.495662,0.482187,0.487262,0.493186,0.515085,0.491575,0.503845,0.530240,0.485162,0.502809,0.516768,0.489427,0.498334
std,0.283240,0.279086,0.296988,0.298569,0.291362,0.295402,0.301673,0.284302,0.289372,0.286095,0.285596,0.292194,0.280777,0.300721
min,0.000696,0.001871,0.001961,0.001764,0.003734,0.004453,0.000385,0.006915,0.003454,0.005811,0.003041,0.002959,0.001246,0.005539
25%,0.255631,0.266064,0.224135,0.215918,0.260302,0.281285,0.229369,0.265371,0.273121,0.241772,0.262711,0.256799,0.260591,0.218935
50%,0.495088,0.507889,0.475474,0.470044,0.497735,0.516433,0.499153,0.514751,0.541544,0.458897,0.481636,0.507273,0.481459,0.506240
75%,0.734957,0.718456,0.736247,0.769015,0.742774,0.782767,0.755795,0.748936,0.787345,0.728347,0.748547,0.772656,0.744711,0.749921
max,0.997092,0.999718,0.996997,0.994205,0.998002,0.999867,0.987022,0.998389,0.999551,0.992232,0.998716,0.991958,0.991891,0.997959

In [18]:
newdf.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
dtype: object

In [19]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.301842,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.321130,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.132730,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.600360,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456

In [20]:
newdf.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
           dtype='int64', length=334)

In [21]:
newdf.columns

RangeIndex(start=0, stop=14, step=1)

In [22]:
#df to array
newdf.to_numpy()

array([[0.30184209, 0.02795051, 0.11190654, ..., 0.11540326, 0.29720187,
        0.21443209],
       [0.32112974, 0.98347082, 0.63805879, ..., 0.4362308 , 0.19450889,
        0.17717795],
       [0.35579234, 0.01881935, 0.09231945, ..., 0.63414444, 0.22254755,
        0.02066055],
       ...,
       [0.65277021, 0.27660534, 0.63707113, ..., 0.69193386, 0.38070179,
        0.3270398 ],
       [0.28571499, 0.50722075, 0.2150292 , ..., 0.82948638, 0.76907984,
        0.69908106],
       [0.48324383, 0.16416185, 0.23193986, ..., 0.69410677, 0.95688789,
        0.8185632 ]])

In [23]:
newdf[0][0]='string'

In [24]:
newdf.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,string,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456

In [25]:
newdf[0][0]=0.3

In [26]:
newdf.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661

In [27]:
newdf[0][0]=0.3

In [28]:
#how to do transpose in df
newdf.T
#rows to col. col to row

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.3,0.32113,0.355792,0.13273,0.60036,0.726246,0.671892,0.495993,0.294247,0.895273,...,0.862558,0.872299,0.472819,0.983751,0.192483,0.358129,0.612788,0.65277,0.285715,0.483244
1,0.027951,0.983471,0.018819,0.56403,0.379509,0.419286,0.897207,0.756652,0.122952,0.117256,...,0.834811,0.600015,0.027652,0.634064,0.54917,0.057036,0.018767,0.276605,0.507221,0.164162
2,0.111907,0.638059,0.092319,0.841582,0.155273,0.304718,0.980766,0.974579,0.319315,0.417497,...,0.646241,0.271429,0.886892,0.397523,0.489503,0.099959,0.33958,0.637071,0.215029,0.23194
3,0.700171,0.162873,0.600081,0.831455,0.648123,0.349568,0.455676,0.674198,0.350012,0.488571,...,0.456591,0.611657,0.816561,0.515602,0.250049,0.276005,0.060804,0.932813,0.736619,0.705894
4,0.98868,0.807268,0.144343,0.041786,0.132037,0.201585,0.793246,0.139226,0.658908,0.601607,...,0.124774,0.515979,0.243351,0.329591,0.64539,0.033724,0.270896,0.478304,0.422675,0.409409
5,0.148973,0.760667,0.450805,0.580494,0.204878,0.380267,0.007508,0.802499,0.780787,0.15028,...,0.235612,0.569045,0.344483,0.980173,0.929093,0.380303,0.149505,0.634644,0.47912,0.532492
6,0.676737,0.967732,0.517543,0.749511,0.098062,0.792467,0.724472,0.411549,0.501845,0.080019,...,0.76586,0.647889,0.987022,0.496461,0.524952,0.179173,0.365227,0.974557,0.172255,0.784064
7,0.985214,0.21926,0.624702,0.587644,0.338531,0.263601,0.224628,0.890752,0.74165,0.574512,...,0.52428,0.323725,0.534956,0.55574,0.285486,0.683636,0.854987,0.329502,0.457491,0.245996
8,0.819313,0.671216,0.136432,0.746133,0.570259,0.951004,0.288958,0.788237,0.866401,0.028771,...,0.238293,0.27929,0.735245,0.344303,0.685561,0.510027,0.877301,0.742198,0.065612,0.783226
9,0.255387,0.576727,0.247638,0.029733,0.949309,0.607452,0.573188,0.939648,0.944687,0.992232,...,0.432392,0.457977,0.566209,0.342895,0.669126,0.650083,0.443648,0.153653,0.249647,0.110318
10,0.405647,0.028036,0.292004,0.313905,0.292956,0.135217,0.782551,0.093825,0.688265,0.74619,...,0.521695,0.480783,0.677948,0.386281,0.177809,0.338685,0.957141,0.223587,0.746452,0.319174
11,0.115403,0.436231,0.634144,0.705646,0.970003,0.966436,0.991958,0.170354,0.19098,0.01297,...,0.979131,0.5138,0.674943,0.464194,0.327679,0.065301,0.652798,0.691934,0.829486,0.694107
12,0.297202,0.194509,0.222548,0.962437,0.514656,0.263618,0.767585,0.659827,0.76668,0.970513,...,0.287329,0.958377,0.244718,0.854069,0.403929,0.433441,0.318714,0.380702,0.76908,0.956888
13,0.214432,0.177178,0.020661,0.968412,0.227456,0.51439,0.190958,0.261276,0.617571,0.528129,...,0.028755,0.666118,0.273744,0.757829,0.112722,0.022415,0.583355,0.32704,0.699081,0.818563

In [29]:
#sorting in row
newdf.sort_index(axis=0,ascending=False)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
0,0.3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432

In [30]:
#sarting in col
newdf.sort_index(axis=1,ascending=False)

,13,12,11,10,9,8,7,6,5,4,3,2,1,0
0,0.214432,0.297202,0.115403,0.405647,0.255387,0.819313,0.985214,0.676737,0.148973,0.988680,0.700171,0.111907,0.027951,0.3
1,0.177178,0.194509,0.436231,0.028036,0.576727,0.671216,0.219260,0.967732,0.760667,0.807268,0.162873,0.638059,0.983471,0.32113
2,0.020661,0.222548,0.634144,0.292004,0.247638,0.136432,0.624702,0.517543,0.450805,0.144343,0.600081,0.092319,0.018819,0.355792
3,0.968412,0.962437,0.705646,0.313905,0.029733,0.746133,0.587644,0.749511,0.580494,0.041786,0.831455,0.841582,0.564030,0.13273
4,0.227456,0.514656,0.970003,0.292956,0.949309,0.570259,0.338531,0.098062,0.204878,0.132037,0.648123,0.155273,0.379509,0.60036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.022415,0.433441,0.065301,0.338685,0.650083,0.510027,0.683636,0.179173,0.380303,0.033724,0.276005,0.099959,0.057036,0.358129
330,0.583355,0.318714,0.652798,0.957141,0.443648,0.877301,0.854987,0.365227,0.149505,0.270896,0.060804,0.339580,0.018767,0.612788
331,0.327040,0.380702,0.691934,0.223587,0.153653,0.742198,0.329502,0.974557,0.634644,0.478304,0.932813,0.637071,0.276605,0.65277
332,0.699081,0.769080,0.829486,0.746452,0.249647,0.065612,0.457491,0.172255,0.479120,0.422675,0.736619,0.215029,0.507221,0.285715
333,0.818563,0.956888,0.694107,0.319174,0.110318,0.783226,0.245996,0.784064,0.532492,0.409409,0.705894,0.231940,0.164162,0.483244

In [31]:
newdf[0]
print("it`s type is ",type(newdf[0]))

it`s type is  <class 'pandas.core.series.Series'>

In [32]:
newdf2=newdf
#here newdf2 is not copinf newdf value but it just refrencing the val

In [33]:
newdf2[0][0]='set in newdf2'

In [34]:
newdf
#newdf is having changes we made in newdf2
#same a pass by refrance' ie. newdf2 is view of newdf

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,set in newdf2,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563

In [35]:
newdf3=newdf.copy()

In [36]:
newdf3

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,set in newdf2,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563

In [37]:
newdf3[0][0]='set in new df3'

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [38]:
newdf
# no changes to df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,set in newdf2,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563

In [39]:
newdf2[0][0]=2323
#this does not have any garety of when it will return view and when it will return copy 
#this we use lock

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [40]:
newdf.loc[0,0]=22

In [41]:
newdf.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,22,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178

In [42]:
newdf.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,22,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178

In [43]:
newdf3.columns=list('asdfghjklpoiuy')

In [44]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563

In [45]:
#how to add new col to trable
newdf3[0]=898

In [46]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178,898
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [47]:
#how to delete in table in df
#how to delete  a row
newdf3.drop(0)
# how to delete a coloum
newdf3.drop(0,axis=1)

,a,s,d,f,g,h,j,k,l,p,o,i,u,y
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563

In [48]:
#newdf3.drop((0,0),axis=1)

In [49]:
newdf3.loc[[1,2],['a','s']]

          a         s
1   0.32113  0.983471
2  0.355792  0.018819

In [50]:
newdf3.loc[[1,2],:]

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178,898
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898

In [51]:
newdf3.loc[:,['a','s']]

                  a         s
0    set in new df3  0.027951
1           0.32113  0.983471
2          0.355792  0.018819
3           0.13273  0.564030
4           0.60036  0.379509
..              ...       ...
329        0.358129  0.057036
330        0.612788  0.018767
331         0.65277  0.276605
332        0.285715  0.507221
333        0.483244  0.164162

[334 rows x 2 columns]

In [52]:
newdf3.loc[newdf3['s']>0.373329]

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178,898
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
5,0.726246,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390,898
6,0.671892,0.897207,0.980766,0.455676,0.793246,0.007508,0.724472,0.224628,0.288958,0.573188,0.782551,0.991958,0.767585,0.190958,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,0.862558,0.834811,0.646241,0.456591,0.124774,0.235612,0.765860,0.524280,0.238293,0.432392,0.521695,0.979131,0.287329,0.028755,898
325,0.872299,0.600015,0.271429,0.611657,0.515979,0.569045,0.647889,0.323725,0.279290,0.457977,0.480783,0.513800,0.958377,0.666118,898
327,0.983751,0.634064,0.397523,0.515602,0.329591,0.980173,0.496461,0.555740,0.344303,0.342895,0.386281,0.464194,0.854069,0.757829,898
328,0.192483,0.549170,0.489503,0.250049,0.645390,0.929093,0.524952,0.285486,0.685561,0.669126,0.177809,0.327679,0.403929,0.112722,898
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898

In [53]:
newdf3.loc[(newdf3['s']>0.373329) & (newdf3['g']>0.5)]

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178,898
6,0.671892,0.897207,0.980766,0.455676,0.793246,0.007508,0.724472,0.224628,0.288958,0.573188,0.782551,0.991958,0.767585,0.190958,898
14,0.322953,0.940453,0.010036,0.831912,0.765228,0.990996,0.976712,0.019947,0.759003,0.649417,0.779131,0.862146,0.606184,0.829191,898
17,0.612306,0.991646,0.148961,0.329158,0.837378,0.033708,0.775600,0.094713,0.005186,0.178107,0.826827,0.172680,0.667112,0.688812,898
20,0.060835,0.558492,0.508832,0.147093,0.605710,0.113900,0.191879,0.089944,0.756549,0.454460,0.397893,0.123209,0.756689,0.555887,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,0.950391,0.988043,0.817826,0.522192,0.922426,0.165208,0.462467,0.054232,0.391119,0.408014,0.574661,0.947093,0.916666,0.471465,898
322,0.18607,0.417320,0.690357,0.737137,0.552441,0.854940,0.359914,0.255698,0.459898,0.147945,0.159313,0.548855,0.147671,0.689416,898
323,0.563389,0.899626,0.604057,0.025638,0.512591,0.507552,0.491499,0.890890,0.343612,0.432613,0.298092,0.557629,0.612112,0.985672,898
325,0.872299,0.600015,0.271429,0.611657,0.515979,0.569045,0.647889,0.323725,0.279290,0.457977,0.480783,0.513800,0.958377,0.666118,898
328,0.192483,0.549170,0.489503,0.250049,0.645390,0.929093,0.524952,0.285486,0.685561,0.669126,0.177809,0.327679,0.403929,0.112722,898

In [54]:
# loc for selcting row and col with ther index name 
# Iloc  for inreting using counting 
newdf3.iloc[0,11]

0.11540326403752388

In [55]:
newdf3.iloc[[0,1],[2,5]]
# this is saying to select  0th and 1 st row and select 2nd and 5th col only

          d         h
0  0.111907  0.148973
1  0.638059  0.760667

In [56]:
newdf3.drop(['a'],axis=1)

,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
1,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178,898
2,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
3,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
4,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
330,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
331,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
332,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
333,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [57]:
newdf3.drop([1])

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
5,0.726246,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [58]:
newdf3
#even after dropin newdf3 is not showing any changes this is because we have not saved it newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
1,0.32113,0.983471,0.638059,0.162873,0.807268,0.760667,0.967732,0.219260,0.671216,0.576727,0.028036,0.436231,0.194509,0.177178,898
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [59]:
#newdf3=newdf3.drop([1])
#or use in   place
newdf3.drop([1],inplace=True)

In [60]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
5,0.726246,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [61]:
# now in newdf3 indix is not proper so we will use reset_index()
newdf3.reset_index()

,index,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
1,2,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
2,3,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
3,4,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
4,5,0.726246,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,329,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
329,330,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
330,331,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
331,332,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
332,333,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [62]:
newdf3.reset_index(drop=True ,inplace=True)

In [63]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,set in new df3,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
1,0.355792,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
2,0.13273,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
3,0.60036,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
4,0.726246,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,0.358129,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
329,0.612788,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
330,0.65277,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
331,0.285715,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
332,0.483244,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [64]:
newdf3['a'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
328    False
329    False
330    False
331    False
332    False
Name: a, Length: 333, dtype: bool

In [65]:
newdf3.loc[:,['a']]=None

In [66]:
newdf3

,a,s,d,f,g,h,j,k,l,p,o,i,u,y,0
0,None,0.027951,0.111907,0.700171,0.988680,0.148973,0.676737,0.985214,0.819313,0.255387,0.405647,0.115403,0.297202,0.214432,898
1,None,0.018819,0.092319,0.600081,0.144343,0.450805,0.517543,0.624702,0.136432,0.247638,0.292004,0.634144,0.222548,0.020661,898
2,None,0.564030,0.841582,0.831455,0.041786,0.580494,0.749511,0.587644,0.746133,0.029733,0.313905,0.705646,0.962437,0.968412,898
3,None,0.379509,0.155273,0.648123,0.132037,0.204878,0.098062,0.338531,0.570259,0.949309,0.292956,0.970003,0.514656,0.227456,898
4,None,0.419286,0.304718,0.349568,0.201585,0.380267,0.792467,0.263601,0.951004,0.607452,0.135217,0.966436,0.263618,0.514390,898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328,None,0.057036,0.099959,0.276005,0.033724,0.380303,0.179173,0.683636,0.510027,0.650083,0.338685,0.065301,0.433441,0.022415,898
329,None,0.018767,0.339580,0.060804,0.270896,0.149505,0.365227,0.854987,0.877301,0.443648,0.957141,0.652798,0.318714,0.583355,898
330,None,0.276605,0.637071,0.932813,0.478304,0.634644,0.974557,0.329502,0.742198,0.153653,0.223587,0.691934,0.380702,0.327040,898
331,None,0.507221,0.215029,0.736619,0.422675,0.479120,0.172255,0.457491,0.065612,0.249647,0.746452,0.829486,0.769080,0.699081,898
332,None,0.164162,0.231940,0.705894,0.409409,0.532492,0.784064,0.245996,0.783226,0.110318,0.319174,0.694107,0.956888,0.818563,898

In [67]:
newdf3['a'].isnull()

0      True
1      True
2      True
3      True
4      True
       ...
328    True
329    True
330    True
331    True
332    True
Name: a, Length: 333, dtype: bool